//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavDBDataTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavFields09vs18
    {
        public int TableNo { get; set; }
        public string TableName2009 { get; set; }
        public string FieldName2009 { get; set; }
        public int FieldNo { get; set; }
        public string FieldName2018 { get; set; }
        public Nullable<int> FieldNeededIn2018 { get; set; }
        public string TableName2018 { get; set; }
        public Nullable<int> TableDeletedIn2018 { get; set; }
        public Nullable<int> TableChangedNameIn2018 { get; set; }
        public Nullable<int> FieldName2009ChangedIn2018 { get; set; }
        public string Type2018 { get; set; }
        public string Class2018 { get; set; }
        public string Enabled2018 { get; set; }
        public string Type2009 { get; set; }
        public string Class2009 { get; set; }
        public Nullable<int> Length2009 { get; set; }
        public Nullable<int> Length2018 { get; set; }
        public Nullable<int> FieldNameLengthChanged { get; set; }
        public Nullable<int> FieldTypeChanged { get; set; }
    }
}
